In [5]:
bd = sorted(map(lambda x: tuple([x.split('|')[0], x.split('|')[1], int(x.split('|')[2])]), open("first_task.txt", "r").read().split("\n")))

user_list = {}
for index, user in enumerate(bd):
    if user[0] not in user_list:
        user_list[user[0]] = {}

    if user[1] not in user_list[user[0]]:
        user_list[user[0]][user[1]] = 0

    user_list[user[0]][user[1]] += user[2]

for key in sorted(user_list):
    print ("%s: %s" % (key, user_list[key]))

Alex Mix: {'cheese': 4}
Ann Metel: {'bread': 2, 'chocolate': 4, 'milk': 6}
Can Yaman: {'coffee': 8}
Irina Vaskova: {'cake': 8, 'milk': 2, 'pie': 9}
John Doe: {'milk': 9}
Veronika Bogdanovich: {'bacon': 2, 'cheese': 2, 'eggs': 5, 'milk': 2}


In [6]:
def main():
    f = open("second_task.txt", "r")

    n = int(f.readline())

    files = {}
    for i in range(n):
        temp = f.readline().split()
        files[temp[0]] = temp[1:]

    print(files)

    m = int(f.readline())
    for i in range(m):
        temp = f.readline().split()
        if temp[1] in files[temp[0]]:
            print("OK")
        else:
            print("Access denied")

    f.close()


main()

{'file1': ['R', 'W'], 'file2': ['X'], 'file3': ['W', 'X'], 'file4': ['R', 'W', 'X'], 'file5': ['W', 'X']}
OK
OK
OK
OK
Access denied
Access denied
Access denied
Access denied
OK
OK


In [8]:
import numpy as np


def main():
    n, m = map(int, input("Enter n, m: ").split())
    print(n, m)

    matrix = np.array([
        [
            m if i == j else (
                m - abs(i - j) if m - abs(i - j) >= n and m >= n else (
                    -abs(i - j) - n if m - abs(i - j) < n <= m else (
                        m + abs(i - j) if m + abs(i - j) <= n and m < n else (
                            -2 * m - abs(i - j) + n if m + abs(i - j) > n > m else 999))))
            for j in range(n)
        ]
        for i in range(n)
    ])

    print(matrix)


main()

Enter n, m: 8 9
8 9
[[  9   8 -10 -11 -12 -13 -14 -15]
 [  8   9   8 -10 -11 -12 -13 -14]
 [-10   8   9   8 -10 -11 -12 -13]
 [-11 -10   8   9   8 -10 -11 -12]
 [-12 -11 -10   8   9   8 -10 -11]
 [-13 -12 -11 -10   8   9   8 -10]
 [-14 -13 -12 -11 -10   8   9   8]
 [-15 -14 -13 -12 -11 -10   8   9]]
